[package]
name = "agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aes-gcm-siv = "0.11.1"
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
base64 = "0.22.1"
chrono.workspace = true
chrono-tz = "0.10.4"
character-context = { path = "../character-context" }
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shared-kernel = { path = "../shared-kernel" }
sqlx.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
